import { SessionProfile } from './types';
import { v4 as uuid } from './uuid';

export const PROFILE_TEMPLATES: SessionProfile[] = [
  {
    id: uuid(),
    name: 'Riding Lesson',
    icon: 'horse',
    intervalSeconds: 120,
    varianceSeconds: 30,
    endCondition: { type: 'afterDuration', seconds: 3600 },
    notes: 'Posture check: heels down, shoulders back, soft hands',
    createdAt: new Date().toISOString(),
    isTemplate: true,
    showOnTimer: true,
  },
  {
    id: uuid(),
    name: 'Strength Circuit',
    icon: 'dumbbell',
    intervalSeconds: 45,
    varianceSeconds: 0,
    endCondition: { type: 'afterCount', count: 15 },
    notes: 'Rest on the buzz, go on the next',
    createdAt: new Date().toISOString(),
    isTemplate: true,
    showOnTimer: true,
  },
  {
    id: uuid(),
    name: 'PT Exercises',
    icon: 'accessibility',
    intervalSeconds: 30,
    varianceSeconds: 0,
    endCondition: { type: 'afterCount', count: 10 },
    notes: 'Hold each stretch/exercise until the next buzz',
    createdAt: new Date().toISOString(),
    isTemplate: true,
    showOnTimer: true,
  },
  {
    id: uuid(),
    name: 'Posture Check',
    icon: 'body',
    intervalSeconds: 300,
    varianceSeconds: 60,
    endCondition: { type: 'afterDuration', seconds: 7200 },
    notes: 'Sit up straight, relax shoulders, unclench jaw',
    createdAt: new Date().toISOString(),
    isTemplate: true,
    showOnTimer: true,
  },
  {
    id: uuid(),
    name: 'Yoga Flow',
    icon: 'fitness',
    intervalSeconds: 60,
    varianceSeconds: 15,
    endCondition: { type: 'afterDuration', seconds: 1800 },
    notes: 'Transition to next pose on the buzz',
    createdAt: new Date().toISOString(),
    isTemplate: true,
    showOnTimer: true,
  },
];
